import type { Metadata } from "next";
import Script from "next/script";
import {
  Cinzel,
  JetBrains_Mono,
  Playfair_Display,
  Space_Grotesk,
} from "next/font/google";
import "./globals.css";
import SessionProvider from "../components/SessionProvider";
import AgeCheckMount from "../components/AgeCheckMount";
import LanguageManager from "../components/LanguageManager";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.variable} ${playfairDisplay.variable} ${cinzel.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <Script id="hb-language-init" strategy="beforeInteractive">
          {`
            (function () {
              try {
                var key = "hb_site_language";
                var stored = localStorage.getItem(key);
                var supported = ["es", "en", "de", "fr", "it", "nl"];
                var lang = supported.indexOf(stored) >= 0 ? stored : "es";
                if (!stored) {
                  localStorage.setItem(key, lang);
                }
                var value = "/auto/" + lang;
                document.cookie = "googtrans=" + value + ";path=/;max-age=31536000";
                document.cookie = "googtrans=" + value + ";path=/";
              } catch (error) {
                document.cookie = "googtrans=/auto/es;path=/;max-age=31536000";
                document.cookie = "googtrans=/auto/es;path=/";
              }
            })();
          `}
        </Script>
        <SessionProvider>
          {children}
          <AgeCheckMount />
          <LanguageManager />
        </SessionProvider>
      </body>
    </html>
  );
}
